### ISSUE TITLE
Planning endpoint returns MultiLineString instead of LineString

### ISSUE THREAD

**Issue by veniversum** [ariadnes-thread/ariadne-route-planner#4]
### Request:
```http
POST /api/v1/planning/route HTTP/1.1
Host: api.ariadnes-thread.me
Authorization: Bearer <REDACTED>
Content-Type: application/json
Cache-Control: no-cache
{
	"constraints": {
		"origin": {
			"longitude": -118.12780,
			"latitude": 34.14175
		},
		"destination": {
			"longitude": -118.12139,
			"latitude": 34.13612
		}
	}
}
```

### Response:
```json
{
    "route": {
        "type": "MultiLineString",
        "coordinates": [
            [
                [
                    -118.1280149,
                    34.141899
                ],
                [
                    -118.1259376,
                    34.1419191
                ]
            ],
            [
                [
                    -118.1257233,
                    34.1326066
                ],
                [
                    -118.1260166,
                    34.1326005
                ],
                [
                    -118.1279402,
                    34.1325605
                ]
            ],
...
```

**Comment by squarespirit** [comment]
We ran into this issue when trying to get a demo working last Friday. If the set of edges doubles back on itself, then ST_Linemerge won't be able to combine them all into a single linestring. (This happens pretty often when we're solving the orienteering problem--we visit a park and leave the way we came.) However the resulting MultiLineString still consists of all the constituent edges, so if you draw it, it still makes sense.

**Comment by TimboKZ** [comment]
The issue is easily solvable via some tweaks to our React map visualisation component. In fact, we wrote a temp fix once already, but it has since been rewritten by a newer version of the webapp. @mvgiambrone is aware of the issue, this temp fix just needs to be incorporated into the main source code of the app and deployed to the server.

**Comment by veniversum** [comment]
I'm positive that it's a bug / regression caused by the new route planner. I have visualized the output from the example request above. The response contains a MultiLineString with 10 segments, visualized on a color scale (red -> blue):

![image](https://user-images.githubusercontent.com/6357330/39518196-119cb260-4db7-11e8-81bc-6052590b55ff.png)

Although the segments are connected, they do **not** form a path (list of edges that connect S -> D) from the source to destination, and the segments aren't provided in the correct order for it to form a path either.

**This is a back end issue, not a front end one.** We shouldn't be 'fixing' the front end to display broken paths, since it'd be incredibly confusing to the user (imagine if the above path wasn't colored). @mvgiambrone 

> If the set of edges doubles back on itself, then ST_Linemerge won't be able to combine them all into a single linestring.

This is not an issue with `ST_LineMerge`, it is capable of handling loops and self-intersections completely fine. Here's a snippet that shows it works with loops / traveling back the same way you took.

```sql
SELECT ST_AsText(ST_LineMerge(ST_GeomFromGeoJSON('{ "type": "MultiLineString", "coordinates": [ [ [ -118.1280149, 34.141899 ], [ -118.1259376, 34.1419191 ] ], [ [ -118.1259376, 34.1419191 ], [ -118.1280149, 34.141899 ] ] ] }')))
```

```sql
LINESTRING(-118.1280149 34.141899,-118.1259376 34.1419191,-118.1280149 34.141899)
```

The problem is that you aren't passing the correct segments into `ST_LineMerge`, or in the incorrect order.

**Comment by squarespirit** [comment]
http://geos.refractions.net/ro/doxygen_docs/html/classgeos_1_1operation_1_1linemerge_1_1LineMerger.html says "Sewing stops at nodes of degree 1 or **3 or more**". And for this query,
```
SELECT ST_AsText(ST_LineMerge(ST_GeomFromGeoJSON(
'{ "type": "MultiLineString", "coordinates": [ [ [ -118, 34 ], [ -118.1280149, 34.141899 ] ], [ [ -118.1280149, 34.141899 ], [ -118.1259376, 34.1419191 ] ], [ [ -118.1259376, 34.1419191 ], [ -118.1280149, 34.141899 ] ] ] }'
)))
```
it still returns a MultiLineString. So I think the issue is the MultiLineString folding back on itself. 

If there are any gaps in the path, that would be a real problem, but I haven't seen that happen yet.

As for the edges not being in order, from just a little bit of testing it seems like ST_LineMerge guarantees nothing about the order of its output. So one solution may be to return the edges in order without using LineMerge, such as
```
        WITH dijkstra AS (
            SELECT *
            FROM pgr_dijkstraVia(
                'SELECT gid AS id, source, target, cost, reverse_cost FROM ways',
                %s)
            ORDER BY seq
        )
        SELECT
            ST_AsGeoJSON(ST_Union(the_geom)) AS geojson, 
            SUM(ways.length_m) AS length
        FROM dijkstra
            JOIN ways ON dijkstra.edge = ways.gid;
```

**Comment by veniversum** [comment]
> So one solution may be to return the edges in order without using LineMerge, such as

`ST_Union` still returns a MultiLineString, so that's not ideal. See #5 for a proposed fix.
